openapi: 3.0.0
x-apiname: catFacts
x-responsetime: 10000
info:
  title: Cat Fact API
  description: Cat facts API
  contact:
    email: admin@admin.com
    url: https://catfact.ninja
  license:
    name: commons
    url: https://catfact.ninja
  termsOfService: yes
  version: 1.0.0
servers:
  - url: https://catfact.ninja
    description: prod
paths:
  /breeds:
    get:
      summary: Returns a list of breeds
      tags:
        - Breeds
      description: Returns a list of breeds
      operationId: getBreeds
      parameters:
        - name: limit
          in: query
          description: This is a description
          required: false
          example: 10
          schema:
            type: integer
            format: int64
            $ref: '#/components/schemas/Breed'
      responses:
        '200':
          description: Normal operation
          content:
            application/json:
              example: success
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Breed'
                $ref: '#/components/schemas/Breed'
        '500':
          description: Server exception
          content:
            application/json:
              example: unsuccessful
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Breed'
                $ref: '#/components/schemas/Breed'
          
  /fact:
    get:
      summary: Returns a random fact
      tags:
        - Facts
      description: Returns a random fact
      operationId: getRandomFact
      parameters:
        - name: max_length
          in: query
          description: maximum length of returned fact
          required: false
          example: success
          schema:
            type: integer
            format: int64
            default: 10
            $ref: '#/components/schemas/Breed'
      responses:
        '200':
          description: Normal response
          content:
            application/json:
              example: success
              schema:
                $ref: '#/components/schemas/CatFact'
        '404':
          description: Fact not found
        '500':
          description: Normal response
          content:
            application/json:
              example: unsuccess
              schema:
                $ref: '#/components/schemas/CatFact'
  /facts:
    get:
      tags:
        - Facts
      summary: Get a list of facts
      description: Returns a a list of facts
      operationId: getFacts
      parameters:
        - name: max_length
          description: length
          in: query
          required: false
          example: success
          schema:
            type: integer
            format: int64
            $ref: '#/components/schemas/CatFact'
        - name: limit
          in: query
          description: limit the amount of results returned
          required: false
          example: success
          schema:
            type: integer
            format: int64
            $ref: '#/components/schemas/CatFact'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              example: success
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatFact'
                $ref: '#/components/schemas/CatFact'
        '500':
          description: successful operation
          content:
            application/json:
              example: unsuccess
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatFact'
                $ref: '#/components/schemas/CatFact'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Breed:
      title: Breed model
      description: Breed
      properties:
        breed:
          title: Breed
          description: Breed
          type: string
          format: string
        country:
          title: Country
          description: Country
          type: string
          format: string
        origin:
          title: Origin
          description: Origin
          type: string
          format: string
        coat:
          title: Coat
          description: Coat
          type: string
          format: string
        pattern:
          title: Pattern
          description: Pattern
          type: string
          format: string
      type: object
    CatFact:
      title: CatFact model
      description: CatFact
      properties:
        fact:
          title: Fact
          description: Fact
          type: string
          format: string
        length:
          title: Length
          description: Length
          type: integer
          format: int32
      type: object
tags:
  - name: Facts
    description: Cat Facts
  - name: Breeds
    description: Breeds
security:
  - BasicAuth: []