openapi: 3.0.0
x-apiname: catFacts
x-responsetime: 10000
info:
  title: Cat Fact API
  contact:
    name: Ronak
    email: admin@admin.com
    url: https://catfact.ninja
  license:
    name: commons
    url: https://catfact.ninja
  termsOfService: yes
  version: 4.0.0
  description: |-
    **The Cat Facts API allows you to programmatically access facts about felines over the internet.** 

    This API returns cat facts that make pussycat lovers giggle with delight. 
    This API provides random cat facts, interesting trivia about cats, and funny sayings about cats.
    Whether you're looking for fun cat facts to share on your Twitter feed, or you need a quick laugh while scrolling through your feed, this API will provide you with plenty of material.
    Its comprehensive collection of adorable cat-related statistics and blurbs about all things felines is sure to keep you entertained for hours.
    The cat facts range from interesting and informative to adorable and heartwarming.
    Each cat fact is accompanied by an accompanying image which, for maximum cuteness factor, is usually a picture of a cat, or a cat themed item.
    So, whether you're looking for something to share on social media, or you just need a smile in your day, this API is sure to provide you with lots of kitty cuteness and fun facts.

    # API Reference
servers:
  - url: https://catfact.ninja
    description: prod
paths:
  /breeds:
    get:
      summary: Returns a list of breeds
      tags:
        - Breeds
      description: Returns a list of breeds
      operationId: getBreeds
      parameters:
        - name: limit
          in: query
          description: This is a description
          required: false
          example: 10
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Normal operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Breed'
        '500':
          description: Server Exception
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Breed'
  /fact:
    get:
      summary: Returns a random fact
      tags:
        - Facts
      description: Returns a random fact
      operationId: getRandomFact
      responses:
        '200':
          description: Normal response
          content:
            application/json:
              example:
                fact: "A cat's normal pulse is 140-240 beats per minute, with an average of 195."
                length: 73
              schema:
                $ref: '#/components/schemas/CatFact'
        '404':
          description: Fact not found
        '500':
          description: Server Exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatFact'
  /facts:
    get:
      tags:
        - Facts
      summary: Get a list of facts
      description: Returns a a list of facts
      operationId: getFacts
      parameters:
        - name: max_length
          description: length
          in: query
          required: false
          example: 20
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: limit the amount of results returned
          required: false
          example: 10
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/CatFact'
        '500':
          description: Server Exception
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/CatFact'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Breed:
      title: Breed model
      description: Breed
      properties:
        breed:
          title: Breed
          description: Breed
          type: string
          format: string
        country:
          title: Country
          description: Country
          type: string
          format: string
        origin:
          title: Origin
          description: Origin
          type: string
          format: string
        coat:
          title: Coat
          description: Coat
          type: string
          format: string
        pattern:
          title: Pattern
          description: Pattern
          type: string
          format: string
      type: object
    CatFact:
      title: CatFact model
      description: CatFact
      required:
        - fact
        - length
      properties:
        fact:
          title: Fact
          description: Fact
          type: string
          format: string
        length:
          title: Length
          description: Length
          type: integer
          format: int32
      type: object
tags:
  - name: Facts
    description: Cat Facts
  - name: Breeds
    description: Breeds
security:
  - BasicAuth: []
